openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: harbor
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: harbor-system
          x-walrus-ui:
            group: Basic
            order: 2
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the Helm chart.
          default: 1.16.0
          x-walrus-ui:
            group: Basic
            order: 3
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for Harbor Helm release.
          default:
            core:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            database:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            jobservice:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            portal:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            redis:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            registry:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            trivy:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 200m
                memory: 512Mi
          additionalProperties:
            properties:
              limits:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Limits
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 1
              requests:
                properties:
                  cpu:
                    title: Cpu
                    type: string
                    x-walrus-ui:
                      order: 1
                  memory:
                    title: Memory
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - cpu
                - memory
                title: Requests
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 2
            required:
            - limits
            - requests
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        replicas:
          title: Replicas
          type: object
          description: Replicas for Harbor pods.
          default:
            core: 1
            database: 1
            jobservice: 1
            portal: 1
            redis: 1
            registry: 1
            trivy: 1
          additionalProperties:
            type: number
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        hpa_core_config:
          title: Hpa Core Config
          type: object
          description: Configuration for the HPA targeting the Harbor core Deployment
          default:
            max_replicas: 5
            min_replicas: 1
            target_cpu_utilization: 80
          required:
          - max_replicas
          - min_replicas
          - target_cpu_utilization
          properties:
            max_replicas:
              title: Max Replicas
              type: number
              x-walrus-ui:
                order: 2
            min_replicas:
              title: Min Replicas
              type: number
              x-walrus-ui:
                order: 1
            target_cpu_utilization:
              title: Target Cpu Utilization
              type: number
              x-walrus-ui:
                order: 3
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        harbor_admin_password:
          title: Harbor Admin Password
          type: string
          description: Admin password for Harbor
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 7
        domain_name:
          title: Domain Name
          type: string
          description: domain name for Harbor, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 8
        issuer_name:
          title: Issuer Name
          type: string
          description: 'origin issuer name for annotation cert-manager.io/issuer:'
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 9
        issuer_kind:
          title: Issuer Kind
          type: string
          description: 'origin issuer kind for annotation cert-manager.io/issuer-kind:'
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 10
      x-walrus-ui:
        groupOrder:
        - Basic
