openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      required:
      - dash_domain_name
      - domain_name
      - environment
      - harbor_admin_password
      - namespace
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: harbor
          x-walrus-ui:
            group: Basic
            order: 1
        namespace:
          title: Namespace
          type: string
          description: The namespace where the Helm release will be installed.
          x-walrus-ui:
            group: Basic
            order: 2
        chart_version:
          title: Chart Version
          type: string
          description: The version of the ingress-nginx Helm chart.
          default: 1.15.0
          x-walrus-ui:
            group: Basic
            order: 3
        harbor_admin_password:
          title: Harbor Admin Password
          type: string
          description: Admin password for Harbor
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 4
        domain_name:
          title: Domain Name
          type: string
          description: domain name for Harbor, e.g. 'domainname.com'
          x-walrus-ui:
            group: Basic
            order: 5
        dash_domain_name:
          title: Dash Domain Name
          type: string
          description: domain name with dash, e.g. 'domainname-com'
          x-walrus-ui:
            group: Basic
            order: 6
        environment:
          title: Environment
          type: string
          description: environment name, e.g. 'dev', 'stg' or 'prod'
          x-walrus-ui:
            group: Basic
            order: 7
      x-walrus-ui:
        groupOrder:
        - Basic
